version: '3.8'
services:
    nginx:
        container_name: nginx-container
        build: ./nginx
        restart: always
        ports:
        - "80:80"
        volumes:
        - web_data:/app
        - ./log:/var/log/nginx
        - ./my_htpasswd:/my_htpasswd
        depends_on:
        - web
    web:
        container_name: web-container
        build: ./myproject
        restart: always
        entrypoint: /app/docker-entrypoint.sh
        command: uwsgi --ini uwsgi.ini
        environment:
          - DJANGO_SUPERUSER_USERNAME=admin
          - DJANGO_SUPERUSER_PASSWORD=admin1234
          - DJANGO_SUPERUSER_EMAIL=admin@haogooday.fun
        volumes:
        - web_data:/app

volumes:
    web_data:

